// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMobDb() {
  return window['go']['main']['App']['GetMobDb']();
}

export function GetSkillDb() {
  return window['go']['main']['App']['GetSkillDb']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
