// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetItemEquipDb():Promise<any>;

export function GetItemEtcDb():Promise<any>;

export function GetItemUsableDb():Promise<any>;

export function Greet(arg1:string):Promise<string>;
