// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetItemEquipDb() {
  return window['go']['main']['App']['GetItemEquipDb']();
}

export function GetItemEtcDb() {
  return window['go']['main']['App']['GetItemEtcDb']();
}

export function GetItemUsableDb() {
  return window['go']['main']['App']['GetItemUsableDb']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
