export const bonus = [
    '1. 最大HP + n (bMaxHP)',
    '2. 最大SP + n (bMaxSP)',
    '3. STR + n (bStr)',
    '4. AGI + n (bAgi)',
    '5. VIT + n (bVit)',
    '6. INT + n (bInt)',
    '7. DEX + n (bDex)',
    '8. LUK + n (bLuk)',
    '9. 最大HP + n% (bMaxHPrate)',
    '10. 最大SP + n% (bMaxSPrate)',
    '11. HP 自然恢復量 + n% (bHPrecovRate)',
    '12. SP 自然恢復量 + n% (bSPrecovRate)',
    '13. 武器[物理]攻擊力 + n% (bAtkRate)',
    '14. [魔法]攻擊力 + n% (bMatkRate)',
    '15. 攻擊速度 + n (bAspd)',
    '16. 攻擊速度 + n% (bAspdRate)',
    '17. 武器[物理]攻擊力 + n (bAtk)',
    '18. 命中率 + n (bHit)',
    '19. [魔法]攻擊力 + n (bMatk)',
    '20. 裝備[物理]防禦力 + n (bDef)',
    '21. 裝備[魔法]防禦力 + n (bMdef)',
    '22. 迴避力 + n (bFlee)',
    '23. 完全迴避力 + n (bFlee2)',
    '24. 爆擊率 + n (bCritical)',
    '25. 減少 x% 受到無屬性攻擊的傷害 (bSubEle,Ele_Neutral)',
    '26. 減少 x% 受到水屬性攻擊的傷害 (bSubEle,Ele_Water)',
    '27. 減少 x% 受到地屬性攻擊的傷害 (bSubEle,Ele_Earth)',
    '28. 減少 x% 受到火屬性攻擊的傷害 (bSubEle,Ele_Fire)',
    '29. 減少 x% 受到風屬性攻擊的傷害 (bSubEle,Ele_Wind)',
    '30. 減少 x% 受到毒屬性攻擊的傷害 (bSubEle,Ele_Poison)',
    '31. 減少 x% 受到聖屬性攻擊的傷害 (bSubEle,Ele_Holy)',
    '32. 減少 x% 受到暗屬性攻擊的傷害 (bSubEle,Ele_Dark)',
    '33. 減少 x% 受到念屬性攻擊的傷害 (bSubEle,Ele_Ghost)',
    '34. 減少 x% 受到不死屬性攻擊的傷害 (bSubEle,Ele_Undead)',
    '35. 減少 x% 受到除了無屬性外全屬性攻擊的傷害 (bSubEle,Ele_Neutral~Ele_Undead)',

    '36. 減少 x% 受到無屬性[物理]攻擊的傷害 (bSubDefEle,Ele_Neutral)',
    '37. 對無屬性目標[物理]攻擊增加 x% 的傷害 (bAddEle,Ele_Neutral)',
    '38. 減少 x% 受到水屬性[物理]攻擊的傷害 (bSubDefEle,Ele_Water)',
    '39. 對水屬性目標[物理]攻擊增加 x% 的傷害 (bAddEle,Ele_Water)',
    '40. 減少 x% 受到地屬性[物理]攻擊的傷害 (bSubDefEle,Ele_Earth)',
    '41. 對地屬性目標[物理]攻擊增加 x% 的傷害 (bAddEle,Ele_Earth)',
    '42. 減少 x% 受到火屬性[物理]攻擊的傷害 (bSubDefEle,Ele_Fire)',
    '43. 對火屬性目標[物理]攻擊增加 x% 的傷害 (bAddEle,Ele_Fire)',
    '44. 減少 x% 受到風屬性[物理]攻擊的傷害 (bSubDefEle,Ele_Wind)',
    '45. 對風屬性目標[物理]攻擊增加 x% 的傷害 (bAddEle,Ele_Wind)',
    '46. 減少 x% 受到毒屬性[物理]攻擊的傷害 (bSubDefEle,Ele_Poison)',
    '47. 對毒屬性目標[物理]攻擊增加 x% 的傷害 (bAddEle,Ele_Poison)',
    '48. 減少 x% 受到聖屬性[物理]攻擊的傷害 (bSubDefEle,Ele_Holy)',
    '49. 對聖屬性目標[物理]攻擊增加 x% 的傷害 (bAddEle,Ele_Holy)',
    '50. 減少 x% 受到暗屬性[物理]攻擊的傷害 (bSubDefEle,Ele_Dark)',
    '51. 對暗屬性目標[物理]攻擊增加 x% 的傷害 (bAddEle,Ele_Dark)',
    '52. 減少 x% 受到念屬性[物理]攻擊的傷害 (bSubDefEle,Ele_Ghost)',
    '53. 對念屬性目標[物理]攻擊增加 x% 的傷害 (bAddEle,Ele_Ghost)',
    '54. 減少 x% 受到不死屬性[物理]攻擊的傷害 (bSubDefEle,Ele_Undead)',
    '55. 對不死屬性目標[物理]攻擊增加 x% 的傷害 (bAddEle,Ele_Undead)',

    '56. 減少 x% 受到無屬性[魔法]攻擊的傷害 (bMagicSubDefEle,Ele_Neutral)',
    '57. 對無屬性目標[魔法]攻擊增加 x% 的傷害 (bMagicAddEle,Ele_Neutral)',
    '58. 減少 x% 受到水屬性[魔法]攻擊的傷害 (bMagicSubDefEle,Ele_Water)',
    '59. 對水屬性目標[魔法]攻擊增加 x% 的傷害 (bMagicAddEle,Ele_Water)',
    '60. 減少 x% 受到地屬性[魔法]攻擊的傷害 (bMagicSubDefEle,Ele_Earth)',
    '61. 對地屬性目標[魔法]攻擊增加 x% 的傷害 (bMagicAddEle,Ele_Earth)',
    '62. 減少 x% 受到火屬性[魔法]攻擊的傷害 (bMagicSubDefEle,Ele_Fire)',
    '63. 對火屬性目標[魔法]攻擊增加 x% 的傷害 (bMagicAddEle,Ele_Fire)',
    '64. 減少 x% 受到風屬性[魔法]攻擊的傷害 (bMagicSubDefEle,Ele_Wind)',
    '65. 對風屬性目標[魔法]攻擊增加 x% 的傷害 (bMagicAddEle,Ele_Wind)',
    '66. 減少 x% 受到毒屬性[魔法]攻擊的傷害 (bMagicSubDefEle,Ele_Poison)',
    '67. 對毒屬性目標[魔法]攻擊增加 x% 的傷害 (bMagicAddEle,Ele_Poison)',
    '68. 減少 x% 受到聖屬性[魔法]攻擊的傷害 (bMagicSubDefEle,Ele_Holy)',
    '69. 對聖屬性目標[魔法]攻擊增加 x% 的傷害 (bMagicAddEle,Ele_Holy)',
    '70. 減少 x% 受到暗屬性[魔法]攻擊的傷害 (bMagicSubDefEle,Ele_Dark)',
    '71. 對暗屬性目標[魔法]攻擊增加 x% 的傷害 (bMagicAddEle,Ele_Dark)',
    '72. 減少 x% 受到念屬性[魔法]攻擊的傷害 (bMagicSubDefEle,Ele_Ghost)',
    '73. 對念屬性目標[魔法]攻擊增加 x% 的傷害 (bMagicAddEle,Ele_Ghost)',
    '74. 減少 x% 受到不死屬性[魔法]攻擊的傷害 (bMagicSubDefEle,Ele_Undead)',
    '75. 對不死屬性目標[魔法]攻擊增加 x% 的傷害 (bMagicAddEle,Ele_Undead)',

    '76. 防具賦予無屬性 (bDefEle,Ele_Neutral)',
    '77. 防具賦予水屬性 (bDefEle,Ele_Water)',
    '78. 防具賦予地屬性 (bDefEle,Ele_Earth)',
    '79. 防具賦予火屬性 (bDefEle,Ele_Fire)',
    '80. 防具賦予風屬性 (bDefEle,Ele_Wind)',
    '81. 防具賦予毒屬性 (bDefEle,Ele_Poison)',
    '82. 防具賦予聖屬性 (bDefEle,Ele_Holy)',
    '83. 防具賦予暗屬性 (bDefEle,Ele_Dark)',
    '84. 防具賦予念屬性 (bDefEle,Ele_Ghost)',
    '85. 防具賦予不死屬性 (bDefEle,Ele_Undead)',
    '86. 空 ()',

    '87. 減少 x% 受到無形種族攻擊的傷害 (bSubRace,RC_Formless)',
    '88. 減少 x% 受到不死種族攻擊的傷害 (bSubRace,RC_Undead)',
    '89. 減少 x% 受到動物種族攻擊的傷害 (bSubRace,RC_Brute)',
    '90. 減少 x% 受到植物種族攻擊的傷害 (bSubRace,RC_Plant)',
    '91. 減少 x% 受到昆蟲種族攻擊的傷害 (bSubRace,RC_Insect)',
    '92. 減少 x% 受到魚貝種族攻擊的傷害 (bSubRace,RC_Fish)',
    '93. 減少 x% 受到惡魔種族攻擊的傷害 (bSubRace,RC_Demon)',
    '94. 減少 x% 受到人類種族攻擊的傷害 (bSubRace,RC_DemiHuman)',
    '95. 減少 x% 受到天使種族攻擊的傷害 (bSubRace,RC_Angel)',
    '96. 減少 x% 受到龍族種族攻擊的傷害 (bSubRace,RC_Dragon)',

    '97. 對無形種族[物理]攻擊增加 x% 的傷害 (bAddRace,RC_Formless)',
    '98. 對不死種族[物理]攻擊增加 x% 的傷害 (bAddRace,RC_Undead)',
    '99. 對動物種族[物理]攻擊增加 x% 的傷害 (bAddRace,RC_Brute)',
    '100. 對植物種族[物理]攻擊增加 x% 的傷害 (bAddRace,RC_Plant)',
    '101. 對昆蟲種族[物理]攻擊增加 x% 的傷害 (bAddRace,RC_Insect)',
    '102. 對魚貝種族[物理]攻擊增加 x% 的傷害 (bAddRace,RC_Fish)',
    '103. 對惡魔種族[物理]攻擊增加 x% 的傷害 (bAddRace,RC_Demon)',
    '104. 對人類種族[物理]攻擊增加 x% 的傷害 (bAddRace,RC_DemiHuman)',
    '105. 對天使種族[物理]攻擊增加 x% 的傷害 (bAddRace,RC_Angel)',
    '106. 對龍族種族[物理]攻擊增加 x% 的傷害 (bAddRace,RC_Dragon)',

    '107. 對無形種族[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_Formless)',
    '108. 對不死種族[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_Undead)',
    '109. 對動物種族[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_Brute)',
    '110. 對植物種族[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_Plant)',
    '111. 對昆蟲種族[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_Insect)',
    '112. 對魚貝種族[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_Fish)',
    '113. 對惡魔種族[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_Demon)',
    '114. 對人類種族[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_DemiHuman)',
    '115. 對天使種族[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_Angel)',
    '116. 對龍族種族[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_Dragon)',

    '117. 對無形種族的爆擊率 + n (bCriticalAddRace,RC_Formless)',
    '118. 對不死種族的爆擊率 + n (bCriticalAddRace,RC_Undead)',
    '119. 對動物種族的爆擊率 + n (bCriticalAddRace,RC_Brute)',
    '120. 對植物種族的爆擊率 + n (bCriticalAddRace,RC_Plant)',
    '121. 對昆蟲種族的爆擊率 + n (bCriticalAddRace,RC_Insect)',
    '122. 對魚貝種族的爆擊率 + n (bCriticalAddRace,RC_Fish)',
    '123. 對惡魔種族的爆擊率 + n (bCriticalAddRace,RC_Demon)',
    '124. 對人類種族的爆擊率 + n (bCriticalAddRace,RC_DemiHuman)',
    '125. 對天使種族的爆擊率 + n (bCriticalAddRace,RC_Angel)',
    '126. 對龍族種族的爆擊率 + n (bCriticalAddRace,RC_Dragon)',

    '127. 無視無形種族目標 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_Formless)',
    '128. 無視不死種族目標 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_Undead)',
    '129. 無視動物種族目標 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_Brute)',
    '130. 無視植物種族目標 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_Plant)',
    '131. 無視昆蟲種族目標 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_Insect)',
    '132. 無視魚貝種族目標 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_Fish)',
    '133. 無視惡魔種族目標 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_Demon)',
    '134. 無視人類種族目標 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_DemiHuman)',
    '135. 無視天使種族目標 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_Angel)',
    '136. 無視龍族種族目標 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_Dragon)',

    '137. 無視無形種族目標 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_Formless)',
    '138. 無視不死種族目標 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_Undead)',
    '139. 無視動物種族目標 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_Brute)',
    '140. 無視植物種族目標 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_Plant)',
    '141. 無視昆蟲種族目標 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_Insect)',
    '142. 無視魚貝種族目標 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_Fish)',
    '143. 無視惡魔種族目標 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_Demon)',
    '144. 無視人類種族目標 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_DemiHuman)',
    '145. 無視天使種族目標 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_Angel)',
    '146. 無視龍族種族目標 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_Dragon)',

    '147. 對一般魔物[物理]攻擊增加 x% 的傷害 (bAddClass,Class_Normal)',
    '148. 對BOSS魔物[物理]攻擊增加 x% 的傷害 (bAddClass,Class_Boss)',

    '149. 減少 x% 受到一般魔物攻擊的傷害 (bSubClass,Class_Norma)',
    '150. 減少 x% 受到BOSS魔物攻擊的傷害 (bSubClass,Class_Boss)',

    '151. 對一般魔物[魔法]攻擊增加 x% 的傷害 (bMagicAddClass,Class_Normal)',
    '152. 對BOSS魔物[魔法]攻擊增加 x% 的傷害 (bMagicAddClass,Class_Boss)',

    '153. 無視一般魔物 n% [物理]防禦力 (bIgnoreDefClassRate,Class_Normal)',
    '154. 無視BOSS魔物 n% [物理]防禦力 (bIgnoreDefClassRate,Class_Boss)',

    '155. 無視一般魔物 n% [魔法]防禦力 (bIgnoreMdefClassRate,Class_Normal)',
    '156. 無視BOSS魔物 n% [魔法]防禦力 (bIgnoreMdefClassRate,Class_Boss)',

    '157. 對小型體型[物理]攻擊增加 x% 的傷害 (bAddSize,Size_Small)',
    '158. 對中型體型[物理]攻擊增加 x% 的傷害 (bAddSize,Size_Medium)',
    '159. 對大型體型[物理]攻擊增加 x% 的傷害 (bAddSize,Size_Large)',
    
    '160. 減少 x% 受到小型體型[物理]攻擊的傷害 (bSubSize,Size_Small)',
    '161. 減少 x% 受到中型體型[物理]攻擊的傷害 (bSubSize,Size_Medium)',
    '162. 減少 x% 受到大型體型[物理]攻擊的傷害 (bSubSize,Size_Large)',

    '163. 刪除武器大小懲罰 (bNoSizeFix,1)',
    '164. 增加 n% 爆擊傷害 (bCritAtkRate)',
    '165. 減少 n% 被爆擊傷害 (bCritDefRate)',
    '166. 增加 n% 遠距離[物理]攻擊傷害 (bLongAtkRate)',
    '167. 減少 n% 被遠距離攻擊的傷害 (bLongAtkDef)',
    '168. 使用所有治癒類技能時, 增加 n% 恢復量 (bHealPower)',
    '169. 接受治癒類技能治療時, 增加 n% 恢復量 (bHealPower2)',
    '170. 減少所有技能的變動詠唱時間 n% (bVariableCastrate,-)',
    '171. 減少所有技能(共通)延遲時間 n% (bDelayrate,-)',
    '172. 所有技能的 SP 消費量 - n% (bUseSPrate,-)',

    '173. 空 ()',
    '174. 空 ()',

    '175. 武器賦予無屬性 (bAtkEle,Ele_Neutral)',
    '176. 武器賦予水屬性 (bAtkEle,Ele_Water)',
    '177. 武器賦予地屬性 (bAtkEle,Ele_Earth)',
    '178. 武器賦予火屬性 (bAtkEle,Ele_Fire)',
    '179. 武器賦予風屬性 (bAtkEle,Ele_Wind)',
    '180. 武器賦予毒屬性 (bAtkEle,Ele_Poison)',
    '181. 武器賦予聖屬性 (bAtkEle,Ele_Holy)',
    '182. 武器賦予暗屬性 (bAtkEle,Ele_Dark)',
    '183. 武器賦予念屬性 (bAtkEle,Ele_Ghost)',
    '184. 武器賦予不死屬性 (bAtkEle,Ele_Undead)',

    '185. 武器不會損壞 (bUnbreakableWeapon,1)',
    '186. 鎧甲不會損壞 (bUnbreakableArmor,1)',

    '187. 對小型體型[魔法]攻擊增加 x% 的傷害 (bMagicAddSize,Size_Small)',
    '188. 對中型體型[魔法]攻擊增加 x% 的傷害 (bMagicAddSize,Size_Medium)',
    '189. 對大型體型[魔法]攻擊增加 x% 的傷害 (bMagicAddSize,Size_Large)',
    '190. 減少 x% 受到小型體型[魔法]攻擊的傷害 (bMagicSubSize,Size_Small)',
    '191. 減少 x% 受到中型體型[魔法]攻擊的傷害 (bMagicSubSize,Size_Medium)',
    '192. 減少 x% 受到大型體型[魔法]攻擊的傷害 (bMagicSubSize,Size_Large)',

    '193. 減少 x% 受到所有屬性攻擊的傷害 (bSubEle,Ele_All)',

    '194. 減少 x% 受到無形種族物理攻擊的傷害 (bSubRace,RC_Formless,getrandomoptinfo(ROA_VALUE),BF_WEAPON)',
    '195. 減少 x% 受到不死種族物理攻擊的傷害 (bSubRace,RC_Undead,getrandomoptinfo(ROA_VALUE),BF_WEAPON)',
    '196. 減少 x% 受到動物種族物理攻擊的傷害 (bSubRace,RC_Brute,getrandomoptinfo(ROA_VALUE),BF_WEAPON)',
    '197. 減少 x% 受到植物種族物理攻擊的傷害 (bSubRace,RC_Plant,getrandomoptinfo(ROA_VALUE),BF_WEAPON)',
    '198. 減少 x% 受到昆蟲種族物理攻擊的傷害 (bSubRace,RC_Insect,getrandomoptinfo(ROA_VALUE),BF_WEAPON)',
    '199. 減少 x% 受到魚貝種族物理攻擊的傷害 (bSubRace,RC_Fish,getrandomoptinfo(ROA_VALUE),BF_WEAPON)',
    '200. 減少 x% 受到惡魔種族物理攻擊的傷害 (bSubRace,RC_Demon,getrandomoptinfo(ROA_VALUE),BF_WEAPON)',
    '201. 減少 x% 受到人類種族物理攻擊的傷害 (bSubRace,RC_DemiHuman,getrandomoptinfo(ROA_VALUE),BF_WEAPON)',
    '202. 減少 x% 受到天使種族物理攻擊的傷害 (bSubRace,RC_Angel,getrandomoptinfo(ROA_VALUE),BF_WEAPON)',
    '203. 減少 x% 受到龍族種族物理攻擊的傷害 (bSubRace,RC_Dragon,getrandomoptinfo(ROA_VALUE),BF_WEAPON)',

    '204. 空 ()',
    '205. 空 ()',

    '206. 減少 x% 受到玩家人類型攻擊的傷害 (bSubRace,RC_Player_Human) ()',
    '207. 減少 x% 受到喵族攻擊的傷害(bSubRace,RC_Player_Doram) ()',

    '208. 對玩家人類型[物理]攻擊增加 x% 的傷害 (bAddRace,RC_Player_Human)',
    '209. 對喵族[物理]攻擊增加 x% 的傷害 (bAddRace,RC_Player_Doram)',

    '210. 對玩家人類型[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_Player_Human)',
    '211. 對喵族[魔法]攻擊增加 x% 的傷害 (bMagicAddRace,RC_Player_Doram)',
    
    '212. 對玩家人類型的爆擊率 + n (bCriticalAddRace,RC_Player_Human)',
    '213. 對喵族的爆擊率 + n (bCriticalAddRace,RC_Player_Doram)',

    '214. 無視玩家人類型 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_Player_Human)',
    '215. 無視喵族 n% [物理]防禦力 (bIgnoreDefRaceRate,RC_Player_Doram)',

    '216. 無視玩家人類型 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_Player_Human)',
    '217. 無視喵族 n% [魔法]防禦力 (bIgnoreMdefRaceRate,RC_Player_Doram)',

    '218. 受到反彈的傷害降低 n% (bReduceDamageReturn)',
    '219. 增加 n% 近距離[物理]攻擊傷害 (bShortAtkRate)',
    '220. 減少 n% 被近距離攻擊的傷害 (bNearAtkDef)',

    '221. 使用無屬性的[魔法]攻擊傷害+ x% (bMagicAtkEle,Ele_Neutral)',
    '222. 使用水屬性的[魔法]攻擊傷害+ x% (bMagicAtkEle,Ele_Water)',
    '223. 使用地屬性的[魔法]攻擊傷害+ x% (bMagicAtkEle,Ele_Earth)',
    '224. 使用火屬性的[魔法]攻擊傷害+ x% (bMagicAtkEle,Ele_Fire)',
    '225. 使用風屬性的[魔法]攻擊傷害+ x% (bMagicAtkEle,Ele_Wind)',
    '226. 使用毒屬性的[魔法]攻擊傷害+ x% (bMagicAtkEle,Ele_Poison)',
    '227. 使用聖屬性的[魔法]攻擊傷害+ x% (bMagicAtkEle,Ele_Holy)',
    '228. 使用暗屬性的[魔法]攻擊傷害+ x% (bMagicAtkEle,Ele_Dark)',
    '229. 使用念屬性的[魔法]攻擊傷害+ x% (bMagicAtkEle,Ele_Ghost)',
    '230. 使用不死屬性的[魔法]攻擊傷害+ x% (bMagicAtkEle,Ele_Undead)',
    '231. 使用全屬性的[魔法]攻擊傷害+ x% (bMagicAtkEle,Ele_All)',

    '232. 擊殺無形種族魔物時增加 n% (基本&職業)經驗值 (bExpAddRace,RC_Formless)',
    '233. 擊殺不死種族魔物時增加 n% (基本&職業)經驗值 (bExpAddRace,RC_Undead) ()',
    '234. 擊殺動物種族魔物時增加 n% (基本&職業)經驗值 (bExpAddRace,RC_Brute) ()',
    '235. 擊殺植物種族魔物時增加 n% (基本&職業)經驗值 (bExpAddRace,RC_Plant) ()',
    '236. 擊殺昆蟲種族魔物時增加 n% (基本&職業)經驗值 (bExpAddRace,RC_Insect) ()',
    '237. 擊殺魚貝種族魔物時增加 n% (基本&職業)經驗值 (bExpAddRace,RC_Fish) ()',
    '238. 擊殺惡魔種族魔物時增加 n% (基本&職業)經驗值 (bExpAddRace,RC_Demon) ()',
    '239. 擊殺人類種族魔物時增加 n% (基本&職業)經驗值 (bExpAddRace,RC_DemiHuman) ()',
    '240. 擊殺天使族魔物時增加 n% (基本&職業)經驗值 (bExpAddRace,RC_Angel) ()',
    '241. 擊殺龍族種族魔物時增加 n% (基本&職業)經驗值 (bExpAddRace,RC_Dragon) ()',
    '242. 擊殺全種族魔物時增加 n% (基本&職業)經驗值 (bExpAddRace,RC_All)',

    '243. POW + n (bPow)',
    '244. SPL + n (bSpl)',
    '245. STA + n (bSta)',
    '246. WIS + n (bWis)',
    '247. CON + n (bCon)',
    '248. CRT + n (bCrt)',
    '249. PATK + n (bPAtk)',
    '250. SMATK + n (bSMatk)',
    '251. RES + n (bRes)',
    '252. MRES + n (bMRes)',
    '253. HPPLUS + n (bHPlus)',
    '254. CRATE + n (bCRate)',
]